-- CONSULTAS SQL
-- Para listar o nome do produto, categoria e a soma total de vendas

SELECT Produto, Categoria, --SELECIONANDO AS COLUNAS PRODUTO E CATEGORIA
       SUM(TOTAL_VENDAS) AS SOMA_TOTAL_VENDAS -- CRIEI UMA NOVA COLUNA PARA SOMA DE TOTAL VENDAS 
FROM data_clean.csv        -- NOME DA MINHA TABELA 
GROUP BY Produto, Categoria   -- ORDENAÇÃO DO GRUPO POR PRODUTOS E CATEGORIA 
ORDER BY SOMA_TOTAL_VENDAS DESC; -- VAI MOSTRAR OS PRODUTOS MAIS VENDIDOS NO TOPO DA CONSULTA 

-- Para identificar os produtos que venderam menos no mês de junho de 2023

SELECT Produto, Categoria,
       SUM(TOTAL_VENDAS) AS SOMA_TOTAL_VENDAS
FROM data_clean.csv
WHERE DATE(Data) BETWEEN '2023-06-01' AND '2023-06-30' -- WHERE VAI UTILIZAR AS BUSCA DE DATAS ENTRE 01 A 30 DE JUNHO NA MINHA TABELA 
GROUP BY Produto, Categoria 
ORDER BY TOTAL_VENDAS ASC; --VAI MOSTRAS OS PRODUTOS MENOS VENDIDOS PRIMEIRO NA CONSULTA 